//question1 
let name = "Gio"; 
let Age = 25; 

console.log(name);
console.log(age);

//question 2

let str = "Hello"; 
let num = 19; 
let isActive = true; 
let nothing = undefined; 

console.log(str);
console.log(num);
console.log(isActive);
console.log(nothing);

//question 3 
let rollNumber = 29; 

if (rollNumber > 10) {
    console.log("The RollNumber is greater than 10");
}
//question 4 
let isMember = true; 

if (isMember) {
    console.log("Member discount applied.");
}
//question 5 
let startValue = 50; // Set startValue

if (startValue > 0) {
    console.log("The value is positive.");
} else if (startValue < 0) {
    console.log("The value is negative.");
} else {
    console.log("The value is zero.");
}
//question 6 
let a = 10;
let b = "10";

console.log(a == b);  
console.log(a === b); 
console.log(a != b); 
console.log(a > b); 
console.log(a < b); 
console.log(a >= b); 
console.log(a <= b); 

//question 7 
let firstName = "giordi";
let lastName = "asdfghj";
let age = 20;

console.log("Hello, " + firstName + " " + lastName + ", you are " + age + " years old.");

//question 8 
let Num = 50;

if (num > 0 && num < 100) {
    console.log("The number is within range.");
}

//question 9 
let hasCar = true;
let hasLicense = true;
let hasInsurance = true;

if (hasCar && hasLicense && hasInsurance) {
    console.log("You can drive legally.");
} else {
    console.log("Check your driving eligibility.");
}

//question 10 
let number = 21

if (num % 2 === 0) {
    console.log("The number is even.");
} else {
    console.log("The number is odd.");
}
//question 11
let score = 85;

if (score >= 90) {
    console.log("Grade A.");
} else if (score >= 80 && score < 90) {
    console.log("Grade B.");
} else {
    console.log("Grade C.");
}

